/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.JOptionPane;

/**
 *
 * @author msham
 */
public class AddPatiant extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddPatiant
     */
    public AddPatiant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AddDate = new de.wannawork.jcalendar.JCalendarComboBox();
        jLable100 = new javax.swing.JLabel();
        txtPatiantNo = new javax.swing.JTextField();
        PatiantNo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBloodNo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        comBloodGroup = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtPname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPAge = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPAdress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comPBirth = new de.wannawork.jcalendar.JCalendarComboBox();
        jLabel11 = new javax.swing.JLabel();
        txtPWeight = new javax.swing.JTextField();
        txtPHeight = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        comPGender = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtPPhoneH = new javax.swing.JTextField();
        txtPPhoneM = new javax.swing.JTextField();
        btnPReset = new javax.swing.JButton();
        btnPNext = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Patiant");
        setPreferredSize(new java.awt.Dimension(1156, 625));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Patiant Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1074, 30));
        getContentPane().add(AddDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 130, -1));

        jLable100.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLable100.setText("Add Date");
        getContentPane().add(jLable100, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 61, 29));

        txtPatiantNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtPatiantNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 84, 71, 32));

        PatiantNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PatiantNo.setText("Patiant No");
        getContentPane().add(PatiantNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 86, 41));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Blood No");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 118, 68, 32));
        getContentPane().add(txtBloodNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 122, 71, 28));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Blood Group");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 156, 87, -1));

        comBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O", "O-", "O+", "A-", "A+", "B+", "B-", "AB" }));
        comBloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBloodGroupActionPerformed(evt);
            }
        });
        getContentPane().add(comBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 156, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 186, 87, 43));

        txtPname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtPname, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 186, 501, 43));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Age");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 235, 60, 30));

        txtPAge.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtPAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 241, 40, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        txtPAdress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPAdressActionPerformed(evt);
            }
        });
        getContentPane().add(txtPAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 500, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 336, -1, -1));

        txtPID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtPID, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 336, 130, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Birth");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 363, 70, 50));
        getContentPane().add(comPBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 382, 130, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Weight");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 383, -1, -1));
        getContentPane().add(txtPWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 383, 46, -1));
        getContentPane().add(txtPHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 414, 46, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Height");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 414, -1, -1));

        comPGender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comPGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(comPGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 423, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Gender");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 423, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Phone");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 476, 40, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Home");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 476, 40, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Mobile");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 506, 40, -1));

        txtPPhoneH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPPhoneHActionPerformed(evt);
            }
        });
        getContentPane().add(txtPPhoneH, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 476, 132, -1));

        txtPPhoneM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPPhoneMActionPerformed(evt);
            }
        });
        getContentPane().add(txtPPhoneM, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 506, 132, -1));

        btnPReset.setBackground(new java.awt.Color(204, 0, 0));
        btnPReset.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnPReset.setText("Reset");
        btnPReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnPReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 544, -1, -1));

        btnPNext.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnPNext.setText("Next");
        btnPNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnPNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 544, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comBloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBloodGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBloodGroupActionPerformed

    private void txtPAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPAdressActionPerformed

    private void txtPPhoneHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPPhoneHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPPhoneHActionPerformed

    private void txtPPhoneMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPPhoneMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPPhoneMActionPerformed

    private void btnPResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPResetActionPerformed
        int YesORNo = JOptionPane.showConfirmDialog(null, "Do you want clear all Text","clear Text", JOptionPane.YES_NO_OPTION);
        if(YesORNo == 0){
            txtBloodNo.setText(null);
            txtPAdress.setText(null);
            txtPAge.setText(null);
            txtPHeight.setText(null);
            txtPPhoneH.setText(null);
            txtPID.setText(null);
            txtPPhoneM.setText(null);
            txtPWeight.setText(null);
            txtPname.setText(null);
            txtPatiantNo.setText(null);
        } else{
            
        }
        
    }//GEN-LAST:event_btnPResetActionPerformed

    private void btnPNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.wannawork.jcalendar.JCalendarComboBox AddDate;
    private javax.swing.JLabel PatiantNo;
    private javax.swing.JButton btnPNext;
    private javax.swing.JButton btnPReset;
    private javax.swing.JComboBox<String> comBloodGroup;
    private de.wannawork.jcalendar.JCalendarComboBox comPBirth;
    private javax.swing.JComboBox<String> comPGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLable100;
    private javax.swing.JTextField txtBloodNo;
    private javax.swing.JTextField txtPAdress;
    private javax.swing.JTextField txtPAge;
    private javax.swing.JTextField txtPHeight;
    private javax.swing.JTextField txtPID;
    private javax.swing.JTextField txtPPhoneH;
    private javax.swing.JTextField txtPPhoneM;
    private javax.swing.JTextField txtPWeight;
    private javax.swing.JTextField txtPatiantNo;
    private javax.swing.JTextField txtPname;
    // End of variables declaration//GEN-END:variables
}
